### ISSUE TITLE
Cant disable Display Custom Menu Items

### ISSUE THREAD

**Issue by iSm1le** [hibbitts-design/grav-theme-quark-open-publishing#16]
After update to v1.4.4 i cant disable Display Custom Menu Items, and always seeing "test entry" in menu.
![Imgur](https://i.imgur.com/1ec0ewH.png)

**Comment by paulhibbitts** [comment]
Hi @iSm1le , thanks very much for letting me know. I've fixed this issue and v.1.4.5 should be available within the hour.

**Comment by iSm1le** [comment]
Looks like its fixed ;)
