### ISSUE TITLE
Archive_plus plugin not visible after upgrade

### ISSUE THREAD

**Issue by NandoPiz** [hibbitts-design/grav-theme-quark-open-publishing#19]
Hi, I've installed skeleton Open Publishing Space.
I've also installed plugin named archive plus instead of pre-existing archive. In order to user archive_plus plugin I've changed file named:
grav\user\themes\quark-open-publishing\templates\partials\sidebar.html.twig
from:
{% if config.plugins.archives.enabled %}

    <div class="sidebar-content">

        <h4>{{ 'THEME_QUARK.SIDEBAR.ARCHIVES.HEADLINE'|t }}</h4>

        {% include 'partials/archives.html.twig' with {'base_url':new_base_url} %}

    </div>

{% endif %}

to

% if config.plugins.archive_plus.enabled %}

    <div class="sidebar-content">

        <h4>{{ 'THEME_QUARK.SIDEBAR.ARCHIVES.HEADLINE'|t }}</h4>

        {% include 'partials/archive_plus.html.twig' with {'base_url':new_base_url} %}

    </div>

{% endif %}

 Is correct that every  upgrade of theme "Quark Open Publishing" i need to modify the file sidebar.html.twig?
Is there a way to avoid to loss this customization when the quark open publishing is updated? 

thank you very much

best regards

**Comment by paulhibbitts** [comment]
Hi @NandoPiz , if I understand correctly you could use an inherited theme to hold your customized Twig so it is not possibly replaced by future updates of Quark Open Publishing.

I've included an inherited theme in the Open Publishing Space called MyTheme. If you placed your modified Twig file `sidebar.html.twig` into the folder `user/themes/mytheme/partials` you will then be safe from future theme updates of this file. 

You can learn more about inherited themes at https://learn.getgrav.org/themes/customization#theme-inheritance

Please let me know if the above solves your issue.

**Comment by NandoPiz** [comment]
Hi, great it works. thank you very much for your help. very appreciated
