### ISSUE TITLE
How to change logo?

### ISSUE THREAD

**Issue by Rikusen0335** [hibbitts-design/grav-theme-quark-open-publishing#2]
I have no idea how do I change the logo.
Could anybody tell me where logo file (like jpg, svg etc.), or any code?

**Comment by paulhibbitts** [comment]
Hi @Rikusen0335 , this is only possible by using custom Twig at the moment. You might find this thread helpful about doing this in the Quark theme (which is the base theme for Quark Open Publishing) https://discourse.getgrav.org/t/changing-logo-gives-black-image/6503/7

You may also want to add your +1 for this enhancement on the Quark repo: https://github.com/getgrav/grav-theme-quark/issues/3

**Comment by paulhibbitts** [comment]
Thanks to the kindness of the theme's developer (Andy Miller) an update to Quark with custom logo support was just released https://twitter.com/getgrav/status/1032705175276933120

I will integrate this work with a new release of Quark Open Publishing shortly.
