### ISSUE TITLE
Small clickable images are not being displayed

### ISSUE THREAD

**Issue by elfrinjo** [hibbitts-design/grav-theme-quark-open-publishing#20]
When using a small image (< 33px) as a link, the image is not being displayed.

This works:
`[![Somewhere](logo.svg?resize=33,33)](https://somewhere.com)`

This does not work:
`[![Somewhere](logo.svg?resize=25,25)](https://somewhere.com)`

* This happens for PNGs as well as SVGs
* The alt-text is not being displayed
* It works in Quark
* In the resulting html, there are different classes assigned to the links:
  * larger, working: `class="external-link image"`
  * smaller, not working: `class="external-link icon"`

**Comment by paulhibbitts** [comment]
Hi @elfrinjo , thanks for reporting the issue. When you say it works in Quark do you mean that the same site (with same plugins etc) with Quark as the Active Theme displays the images? I do not recall making any changes to how images are handled except I do use at least one Plugin related to images (i.e. Image Captions). Could you post here (or DM me in the Grav Discourse chat) your user folder?

**Comment by elfrinjo** [comment]
Hi @paulhibbitts , thanks for hinting the plugins!

As it turns out, the [External Links](https://github.com/sommerregen/grav-plugin-external-links) plugin caused my problem (which is quite expectable when reading the description properly)
Deactivating solves it.

**Comment by paulhibbitts** [comment]
Great to hear you got things sorted!
