### ISSUE TITLE
hamburger menu mobile

### ISSUE THREAD

**Issue by NandoPiz** [hibbitts-design/grav-theme-quark-open-publishing#22]
Hi, I've installed skeleton Open Publishing Space. After the last upgrade of theme "Quark Open Publishing "the humburger menu' for mobile is visible but not working.
I mean that after the upgrade if you click on the hamburber menu this is not able to open anymore. regards

**Comment by paulhibbitts** [comment]
Hi @NandoPiz , thanks very much for reporting this. I've got a lead to the issue and am working on a fix now.

**Comment by paulhibbitts** [comment]
Ok @NandoPiz I just released a theme update which should address this issue, please let me know if it works for you.

**Comment by NandoPiz** [comment]
Hi. Thak you very much for your job. I cannot see the theme update (versione 1.6.1) I can only see version 1.6.0 using normal update theme procedure with admin GUI interface

**Comment by paulhibbitts** [comment]
I am not sure why that would be the case, the updated 1.61 version is listed on https://getgrav.org/downloads/themes

Is the update in Admin working for you now? If not, you could manually update the needed file:
https://github.com/hibbitts-design/grav-theme-quark-open-publishing/blob/master/templates/partials/base.html.twig

Please let me know if you can get things going.

**Comment by NandoPiz** [comment]
the update is visible now and works perfectly. Hamburger menu works fine thank you very much. regards

**Comment by paulhibbitts** [comment]
Great, thanks for letting me know @NandoPiz !
