### ISSUE TITLE
Feature request: in sections navigation on the left

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-theme-quark-open-publishing#25]
The template /quark-open-publishing/templates/sections.html.twig renders by default the navigation on the right side of the content.
Is it possible to have/add an entry in the **Sections Config** where I can choose to render the navigation on the left-side or the right-side?

![image](https://user-images.githubusercontent.com/12153667/63006819-b64af300-be7f-11e9-9af4-1d1047affd30.png)

**Comment by paulhibbitts** [comment]
Hi @awrog , this is a great suggestion - I've got this option now in Bootstrap4 Open Matter as well. I will look into this and see what I can come up with.

**Comment by paulhibbitts** [comment]
Hi @awrog , I've looked into this and now remember why I did not support this to begin with🙂 Right now the Spectre CSS framework does not support column ordering (https://github.com/picturepan2/spectre/issues/274) while Bootstrap4 does - and that is how I was able to provide this open in Bootstrap4 Open Matter.

I am sorry but at this time I can't provide this option. I will however keep it in mind and see if another approach might be possible.

**Comment by awrog** [comment]
Hi Paul,

Thanks for helping me out!!
Exactly what I [ended up withdid](https://lrp-netwerk.pkn.nl/geldwerving).

Isn't it possible to control it via a toggle/boolean?

Kind of:

```
{% if toggle = true %}
...
<div id="sections-nav" class="column col-3 col-md-12">
<div id="sections-content" class="column col-9 col-md-12">
...
{% else %}
...
<div id="sections-content" class="column col-9 col-md-12">
<div id="sections-nav" class="column col-3 col-md-12">
...
{% endif %}

```
Or am I thinking too simplistic?

**Comment by paulhibbitts** [comment]
The logic is straightforward to add the toggle, it is the CSS required to re-order the Sections content and navbar based on that toggle. As I mentioned, with Bootstrap4 Open MatterI was able to do this cleanly (as seen here https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter/blob/master/templates/sections.html.twig#L49-L53) but Spectre does not support that. There might be another way to do this though - always open to alternative options that minimally change the theme🙂

**Comment by awrog** [comment]
I'm afraid you've lost me there. (no biggy)
For my purpose just switching the navigation and content makes me content with the result 🙂

Keep up the good work!!

**Comment by paulhibbitts** [comment]
Sorry if that was clear - as the Twig will display the Sections content before the navbar the CSS must actually swap that to display the navbar on the left (i.e. first)... hope that is a bit clearer.

I will close this issue now but will keep this in mind as a possible future enhancement.

Thanks for the positive feedback, glad you are finding the theme useful!
