### ISSUE TITLE
Update via Admin Panel fails

### ISSUE THREAD

**Issue by MakaryGo** [hibbitts-design/grav-theme-quark-open-publishing#27]
2.0.1 => 2.0.3 (latest

Update via Admin Panel says that Quark is missing ald subsequently fails while trying to install it.
Update via GPM also says Quark is missing, but apparently manages to install it.

**Comment by paulhibbitts** [comment]
Hi @MakaryGo , thanks for the issue report. I just tried an update on a local test and all seemed fine, might it be related to a server permissions issue or something? Unfortunately with every update Grav will report re-installing the needed parent theme (Quark). Might there be another site you can try an update on too? Thanks!

**Comment by MakaryGo** [comment]
I'll try :)

**Comment by paulhibbitts** [comment]
Thanks! Just tried an update to my online test site and that seems ok too.

**Comment by MakaryGo** [comment]
Apparently it's some weird bug on my server... Which is actually strange, as I use Grav for a long time and never encountered it before...
getgrav/grav-plugin-admin/issues/1719

**Comment by paulhibbitts** [comment]
Glad you got things going @MakaryGo!
