### ISSUE TITLE
Latest update causes problems (same like #27)

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-theme-quark-open-publishing#28]
The update of this theme states that 'Quark' is not installed. It is.
Also the plugin 'presentation-deckset' is missing, it is not
The installation of it causes an error (reported with Ole Vik)

See attachment 

![update-theme](https://user-images.githubusercontent.com/12153667/71085439-d70db700-2197-11ea-9137-558f487e0765.gif)

**Comment by paulhibbitts** [comment]
Hi @awrog , thanks for reporting the issue. When updating an inherited theme (like QOP) there will always be a note about the dependent theme being installed (Quark), however you should not be getting that error re: deckset. 

Could you please confirm that the site you are updating has both the Presentation Plugin and the Presentation Plugin?

Thanks very much,
Paul

**Comment by paulhibbitts** [comment]
I am trying to replicate the issue, and an update from Quark v1.9.4 to the current release (v2.0.5) works locally - I will try to locate a skeleton with v2.0.3 to test as well.

**Comment by awrog** [comment]
I could send you a full backup...

**Comment by paulhibbitts** [comment]
Sure thing, my email address is paul@hibbittsdesign.org. Might have any server changes been done recently? Issue #27 seemed to be related to that too.

**Comment by awrog** [comment]
I figured it out. the offending file was \user\config\plugins\presentation.yaml
Although I've never used the plugin Presentation, the config-file seems incompatible with the latest version of the plugin.
Just deleting the old presentation.yaml and reopening and saving the plugin solves the problem!

**Comment by paulhibbitts** [comment]
Glad you got things going @awrog . I've also been in touch with, Ole and he has also worked out an approach for the Presentation Deckset Plugin to prevent this issue in the future.

**Comment by awrog** [comment]
Great, love Grav and the support from you guys!
