### ISSUE TITLE
Enable comments for blog posts?

### ISSUE THREAD

**Issue by zaszlo** [hibbitts-design/grav-theme-quark-open-publishing#3]
I would like to use the comments plugin by the grav team. It is enabled (see it from admin panel) and I see it is included in this theme in templates/partials/blog-item.html.twig:
```
{% if page.header.continue_link is sameas(true) and config.plugins.comments.enabled %}
        {% include 'partials/comments.html.twig' %}
{% endif %}
```
What could be the reason that it is not appearing on the bottom of the blog posts?

Thanks!

**Comment by paulhibbitts** [comment]
Hi @zaszlo , I just downloaded the current Open Publishing Space skeleton (using Quark Open Publishing) and installed the Comments Plugin and it seemed to work:

![2018-09-02_08-10-37](https://user-images.githubusercontent.com/1812771/44957452-b37e0a80-ae87-11e8-9bd2-e3c06579a791.png)

Are you installing the Comment Plugin in the OPS skeleton or another site using the Quark Open Publishing theme?

**Comment by zaszlo** [comment]
Thanks for the feedback, tried with the modified snippet, but still the comment section didn't appear... any other hints on how to debug what is going on?

**Comment by paulhibbitts** [comment]
Did you clear the cache for your test (system.yaml file, both caches or via Admin Panel)? Also confirm that your active theme is the theme files you are editing - thanks!

**Comment by zaszlo** [comment]
I did clear the cache with method "all" and am using the My Quark Theme with only minor additions in templates copied from Quark Open Publishing:
item.html.twig 
partials/blog-item.html.twig
partials/navigation.html.twig

The partials having the edit that you suggested here. But did that edit on both My theme and on the Quark Open Publishing.

```
...
        {% else %}
            {{ page.summary }}
        {% endif %}
    </div>

    {% if config.plugins.comments.enabled %}
        {% include 'partials/comments.html.twig' %}
    {% endif %}

</div>

{# added check for content display flag - hibbittsdesign.org #}
{% if not (grav.uri.param('chromeless')) %}
...
```
Interestingly if I add 

```
    {% if config.plugins.comments.enabled %}
        OK
        {% include 'partials/comments.html.twig' %}
    {% endif %}
```

The OK is rendered fine. I installed the comments plugin from admin console and checked that it is enabled, did not touched it otherwise.

**Comment by paulhibbitts** [comment]
Hmm... I've made a new release of the theme with the above fix, perhaps try that?

I've also released a new Open Publishing Space skeleton with the new theme, you could download and test that to make sure there are no issues with your specific setup etc. https://getgrav.org/downloads/skeletons

**Comment by zaszlo** [comment]
It was my bad that I didn't created a new comments.yaml into my config/plugins and didn't changed the default enabled route from blog to home.

**Comment by paulhibbitts** [comment]
Glad you got things going!

**Comment by LeMoussel** [comment]
Hi Paul,

I'm tested Open Publishing Space skeleton with the Comments Plugin. 

![image](https://user-images.githubusercontent.com/1816573/90329906-df2d2900-dfa8-11ea-8146-1889da3ad84b.png)

I got this error: 

> Whoops \ Exception \ ErrorException (E_NOTICE)
> Trying to access array offset on value of type null

![image](https://user-images.githubusercontent.com/1816573/90329912-f3712600-dfa8-11ea-9b2d-3b98905c522d.png)

I copy the contents of `user/plugins/comments/comments.yaml` in `user/config/plugins/comments.yaml`.
However, I notice that there is `user/data/comments` folder.  This seems normal to me because there are no comments on the articles.

**Comment by paulhibbitts** [comment]
Thanks for letting me know @LeMoussel 🙂
