### ISSUE TITLE
Hero Blog will not display gif as 'Hero image' (header)

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-theme-quark-open-publishing#32]
grav-theme-quark-open-publishing, inherited theme
Home page: type blog
Blog Config => Hero Image: select an (animated) gif (the only image available)
The image is not being displayed (works fine with a png/jpg)
Test: edit hero.html.twig:
```
{% if hero_image %}style="background-image: url('/user/pages/01.blog/header.gif');"{% endif %} 
```
...and it works.
Looks like Hero_Image does not 'accept' (animated) gifs.
I use animated gif (huge) for an animated header (in lieu of a mp4/webm which I cannot select (for obvious reasons))
The addition of being able to display a mp4/webm for Hero Header Image would be just awsome!

**Comment by paulhibbitts** [comment]
Hi @awrog , this might be something to do with site config... this thread might provide some clues? https://discourse.getgrav.org/t/animated-gifs-not-showing-at-quark-blog-list-page/7222/4

Please let me know if you can get things going.
