### ISSUE TITLE
Grav is giving error during deploying

### ISSUE THREAD

**Issue by ghtmtt** [hibbitts-design/grav-theme-quark-open-publishing#33]
Hi Paul,

I was deploying the website locally before to publish on the server, but I'm getting the following error:
```

Server Error

Sorry, something went terribly wrong!
E_WARNING - require_once(): \RocketTheme\Toolbox\StreamWrapper\ReadOnlyStream::stream_set_option is not implemented!
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

In `user/themes` I've 3 folders: 

`mytheme`
`quark`
`quark-open-publishing`

`mytheme` is inheriting from `quark-open-publishing` and during a trial and error I discovered that `mytheme.php` is the guilty. By removing it , the site works. This is the content:
```

<?php
namespace Grav\Theme;

use Grav\Common\Theme;

class myTheme extends QuarkOpenPublishing
{
}
?>
```

do you have some ideas?

**Comment by paulhibbitts** [comment]
Hi @ghtmtt , can you give me a few more details of the site you are trying to deploy? Was this a new skeleton or an existing site updated? What version of Grav and PHP are you running?

**Comment by ghtmtt** [comment]
Right, sorry for the few information.

Grav Package Manager 1.6.22
PHP 7.4.3 (cli) (built: Feb 23 2020 07:07:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

on a Linux Debian Sid computer.

The webiste (running) is this: https://www.faunalia.eu/it/

I created the site based on both quark and quark-open-publishing. Just added some css and layout stuff.

**Comment by paulhibbitts** [comment]
I've seen some mentions of possible issues with PHP 7.4.x, can you try the site with an earlier version of PHP?

**Comment by ghtmtt** [comment]
trying with another version of PHP can be a little bit hard. Have to adapt the whole ecosystem..

that's strange that by removing one single file it works smoothly..

**Comment by paulhibbitts** [comment]
By using an inherited theme other routines might be called etc. I notice you posted an issue on Grav's repo to (https://github.com/getgrav/grav/issues/2850) so let's see if that is responded to.

**Comment by ghtmtt** [comment]
yep, let's see. Thanks for the quick answer.
