### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-theme-quark-open-publishing#34]
It would be great if I could schedule the display of modular content (an alert) in the blog section.

When ```published: true``` the modular/alert gets published
When ```published: false``` the modular/alert does not get published (which is as intended)
Setting a ```publish_date``` (without ```published: true```) does not seem to have any effect.
Is it that possible to have a functional publish_date (and unpublish_date) for modular blog content? (just like 'ordinary' blog posts?)

Thanks in advance!

**Comment by awrog** [comment]
Perhaps it can be done with a filter in the modular_content section of the blog page?

**Comment by paulhibbitts** [comment]
Hi @awrog , I looked into this a bit and it seems this is handled by Grav itself vs the theme (at least from what I can tell). Something might still be possible via custom Twig but that would be a very specialized change.

**Comment by awrog** [comment]
Thanks for having a look at it!
