### ISSUE TITLE
Twitter feed not showing anything

### ISSUE THREAD

**Issue by ghtmtt** [hibbitts-design/grav-theme-quark-open-publishing#35]
Hi,

using the last version of the theme and customized the folder `sidebar` within `user/pages` to just match the correct twitter account. But the sidebar with the Twitter card seems broken:

![image](https://user-images.githubusercontent.com/2884884/82222362-738fdd00-9921-11ea-9e02-15e15a9c4a6c.png)

and this is the content of the `sidebar/default.md` file:

```
---
title: Sidebar
routable: false
visible: false
position: top
---

[twitter url="https://twitter.com/FaunaliaGIS" text="Tweets by @FaunaliaGIS" height="600"]
```

**Comment by paulhibbitts** [comment]
Hi @ghtmtt , I can't seem to replicate this issue. My online demo site (https://demo.hibbittsdesign.org/grav-open-publishing-quark/) is still showing the Twitter feed as is my local test site.

Are you still seeing this issue? What version of Grav are you using?
Paul

**Comment by ghtmtt** [comment]
Hi @paulhibbitts weird... 

Grav version is 1.6.22

I'm debugging it locally but also in production

**Comment by paulhibbitts** [comment]
If you would like you could send me your `user` folder on Discord (https://discord.gg/5VhYVkR) and I could test on my local setup. Maybe another Plugin is causing a conflict?
