### ISSUE TITLE
Link chromeless 404

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-theme-quark-open-publishing#36]
The item "chromeless" in the menu links to 
`http://demo.hibbittsdesign.org/grav-theme-bootstrap4-open-matter/blog/chromeless:true` (404)

This should be
`http://demo.hibbittsdesign.org/grav-theme-bootstrap4-open-matter/chromeless:true`

**Comment by paulhibbitts** [comment]
Thanks for catching that @awrog , I recently updated the example site content and forgot that menu link🙂 http://demo.hibbittsdesign.org/grav-theme-bootstrap4-open-matter/
