### ISSUE TITLE
Add a setting for date translations

### ISSUE THREAD

**Issue by LeMoussel** [hibbitts-design/grav-theme-quark-open-publishing#37]
By default, dates are not translated in Grav, which is a concern for internationalization.

One way to get dates localized would be to use the Twig extensions plugin that will localize dates : https://github.com/Perlkonig/grav-plugin-twig-extensions.
The filter `localizeddate('long', 'short', html_lang)`  does the job to get a localized datetime format.

I setup a test site with a `date.html.twig`:
```
<span class="blog-date">
    <time class="dt-published" datetime="{{ page.date|date("c") }}">
        <!-- => older <i class="fa fa-calendar"></i> {{ page.date|date(system.pages.dateformat.short) }} -->
        <i class="fa fa-calendar"></i> {{ page.date|localizeddate('long', 'short', html_lang) }}
    </time>
</span>
```
For french I Got this:
![image](https://user-images.githubusercontent.com/1816573/90865105-2ee96700-e392-11ea-8035-c4900d6fc0a7.png)

This could be integrated by default in this theme

**Comment by paulhibbitts** [comment]
I am closing this for now, hope your custom Twig works well for you!
