### ISSUE TITLE
{{ 'THEME_QUARK.SIDEBAR.____' }} isn't parsed in browser

### ISSUE THREAD

**Issue by haverholm** [hibbitts-design/grav-theme-quark-open-publishing#38]
I'm newish to Grav, and setting up a new site using the QuarkOP skeleton, and for some reason the {{ 'THEME_QUARK.SIDEBAR.___' }} (twig?) functions  just show up as... THEME_QUARK.SIDEBAR.___ in the browser. That goes for sidebar headers (popular tags, archives and syndication) as well as the "read more..." button on blog item cards.

![Screenshot_2020-09-25 Home Quark OP(1)](https://user-images.githubusercontent.com/5727354/94256993-edb51b80-ff2a-11ea-931d-9d0c3f2743bc.png)
![Screenshot_2020-09-25 Home Quark OP](https://user-images.githubusercontent.com/5727354/94256997-ee4db200-ff2a-11ea-92bf-aed5b88b384d.png)

So far I've only used the admin panel to edit the site, and have seen no option to customize those strings. Nor do I find any sign in the repo issues that this happened for others. Is there some theme config file I'll need to crack open to set this, or is it some weird php setting on my (hosted) server that needs adjusting?

**Comment by paulhibbitts** [comment]
Did you ever solve this issue? Sorry that I did not notice this issue sooner!
