### ISSUE TITLE
scss source?

### ISSUE THREAD

**Issue by zaszlo** [hibbitts-design/grav-theme-quark-open-publishing#39]
Hello, 

There is a theme.css in the css directory but I can't find the modified scss in this theme, but in the readme it features it as "SCSS based CSS source files for easy customization".

Thanks!

**Comment by paulhibbitts** [comment]
Hi @zaszlo , I did not use SCSS when creating this inherited theme. The base theme, Quark, does use SCSS I believe https://github.com/getgrav/grav-theme-quark. Hope that info helps!

**Comment by zaszlo** [comment]
Hi @paulhibbitts, 

I see that the open publishing theme uses some extra classes and if those are missing, the theme breaks in obvious ways, like showing the h1 title (has hidden class). 

I edited the quark scss because just adding my custom extra css doesnt take priority over the base, and is more adequate to use that scss than to load a chain of csses with ! to try and prioritize the css rules. 

It would be more practical for customization to have the open-publishing css rules ie separate css or commented in the modified quark scss files. 

Otherwise I'm left to just debug the theme and extract the classes that I find missing. If this is the case the feature of using the quark scss in the readme should be omitted and maybe a warning should be presented.

Thanks!

**Comment by paulhibbitts** [comment]
Thanks for the additional info @zaszlo , your idea of making a note in the ReadMe is a very good suggestion so I will do that next release. Sorry that you ran into this issue.
