### ISSUE TITLE
svg logo

### ISSUE THREAD

**Issue by zaszlo** [hibbitts-design/grav-theme-quark-open-publishing#4]
The logo can be changed by putting a file in the images/logo directory and calling it from the theme's yaml file, like:
```
custom_logo:
  -
    name: xyz.svg
```
The problem is that this renders the svg as an image, not as on the demo page with plain svg, so having a black&white svg like in the demo wont be switched when having light or dark background... I think the solution would be to render svg's in the way it is in the demo. Tried to override this by naming my logo to grav-logo.svg and putting it to my active theme's iamges folder but keeps reading the default grav-logo.svg from the parent theme.
Replacing the grav-logo.svg from quark theme solves the problem... until the next update.

**Comment by paulhibbitts** [comment]
Hi @zaszlo , I don't think my theme chances anything related to Logo handling, which was just added to Quark recently.

**Comment by zaszlo** [comment]
Thanks @paulhibbitts for pointing to that chat room! I'll move the issue to the quark theme.
