### ISSUE TITLE
how to inherit from this 'inherited' theme?

### ISSUE THREAD

**Issue by lustyffh** [hibbitts-design/grav-theme-quark-open-publishing#42]
Hi, I'd like to make use of the grav inheriance feature. But inheriting this theme doesn't seem to work. Also, "class Mytheme extends quark-open-publishing" doesn't seem to work as class name doesn't allow hyphens.

**Comment by paulhibbitts** [comment]
Hi @lustyffh , this is all setup in the Open Publishing Skeleton with a pre-built 'mytheme' , available at https://getgrav.org/downloads/skeletons

Please let me know if you can get things going from there etc.

**Comment by paulhibbitts** [comment]
Closing this, but please feel free to re-open.

**Comment by lustyffh** [comment]
@paulhibbitts Thanks a lot! As to the `class Mytheme extends` - the key was to type in theme name omitting hyphens - something not mentioned explicitly in Theme Inheritance documentation. Also, one shouldn't forget to copy all theme configurations in `user/config/themes` to the new theme file.
