### ISSUE TITLE
Question filter view

### ISSUE THREAD

**Issue by fugo** [hibbitts-design/grav-theme-quark-open-publishing#43]
What is the differnce and meaning of the filter in the multi-section-pages?  
I mean this
```
taxonomy:
    filter:
        - view1
        - view2
``` 
and ``filter: [view1]`` ``filter: [view2]``. I can’t find any information about that.

TIA

**Comment by paulhibbitts** [comment]
Hi @fugo , thanks for your question.

Basically `filter` is a pre-defined Grav Taxonomy (https://learn.getgrav.org/17/content/taxonomy) item supported by multi-section pages.

As you have discovered, the Open Publishing Space Skeleton using the Quark Open Publishing Theme includes an example. The online demo also has the same example.

So, by default all multi-section pages are displayed with the URL:
https://demo.hibbittsdesign.org/grav-open-publishing-quark/multi-section-page

However, let's say you want to use `filter` to only display multi-section pages with the taxonomy item `view1`:
https://demo.hibbittsdesign.org/grav-open-publishing-quark/multi-section-page/filter:view1

Please let me know if the above helps etc.
Paul

**Comment by fugo** [comment]
Thank you very much. :+1: I have a bit a clue about taxonomy but didn’t about the ``filter:view`` So it’s working like a *tag* filter but only for multi sections pages (depending on the ``sections.html.twig`` thought).

I asked because I want to use your multi section pages in another theme (darkquark).
It was exactly what I want but my **twig** experience are not so good :smirk:
