### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by BigDC** [hibbitts-design/grav-theme-quark-open-publishing#44]
Is there a version of Quark Open Publishing that will work on grav v1.69, as I can not upgrade my php in order to get grav 1.7x, is there as I really would love to use this theme?

**Comment by paulhibbitts** [comment]
Hi @BigDC , the current version should work fine as it should only need Grav 1.6 or greater. Are you running into an issue?

**Comment by BigDC** [comment]
Yes I am. I download the current version for this repo,I upload the inner **grav-theme-quark-open-publishing-master** directory and its contents to my grav themes folder, but when I go to activate it in grav admin it doesn't even show the theme as even being there, please help???

**Comment by paulhibbitts** [comment]
I would suggest you install the theme via the Admin Panel or the GPM (as described on this page): https://getgrav.org/downloads/themes

**Comment by BigDC** [comment]
I tried renaming the the theme folder to quark-open-publishing still no luck

So I deleted the entire folder from themes and I actually tried doing it via the Admin Panel but it gave me an error saying one of the packages requires grav 1.7.21

**Comment by BigDC** [comment]
Oops, my bad. I forgot to remove the word master from the name when I renamed it, I just did that now and it has installed manually.
