### ISSUE TITLE
Feed plugin breaks the main page

### ISSUE THREAD

**Issue by jakubtalich** [hibbitts-design/grav-theme-quark-open-publishing#49]
Turrning the Feed plugin off and then on again breaks the main page.
![Screenshot 2023-10-20 at 14-03-14 Home UNIXWorld](https://github.com/hibbitts-design/grav-theme-quark-open-publishing/assets/128613548/b7a81830-28ca-4e6a-ab66-aa340d928b0b)

Any idea what the cause might be? The issue is still visible at unixworld.cz

Thanks

**Comment by paulhibbitts** [comment]
Hi @jakubtalich , I really don't know - I just tested with the open publishing skeleton demo and saw no issue there. Perhaps clear the cache after you turn it on or off? Also, it might be an idea to use the parent Quark theme and see if the issue persists on that setup. Hope that helps, Paul.

**Comment by jakubtalich** [comment]
I reinstalled the template. Thank you.

**Comment by paulhibbitts** [comment]
Great, glad you were able to get things going a-ok. Thanks for letting me know.
