### ISSUE TITLE
date language for the archive section

### ISSUE THREAD

**Issue by zaszlo** [hibbitts-design/grav-theme-quark-open-publishing#5]
I have managed to set other language for the theme than English, set the language site wide but still the archive section's dates come with English month names. 
Any hints on how to change that? Or make it so that it uses the already set language for the theme when rendering a date in the archive section.

**Comment by paulhibbitts** [comment]
This might be an issue with the Archives Plugin? https://github.com/getgrav/grav-plugin-archives/issues/8

**Comment by paulhibbitts** [comment]
Could you please see if this issue is related to the Quark Open Publishing theme by testing with another theme and letting me know the results @zaszlo ? Thanks very much.

**Comment by zaszlo** [comment]
I changed it to Quark and it gave the same date strings so, no it is not related with this theme.

**Comment by Batnik** [comment]
i can confirm the problems, month names are not translated.

**Comment by Neilerua13** [comment]
Dates do not translate for me too ... For articles as for archives

**GRAV** : Stable Version 1.5.5
**THEME :** Quark
