### ISSUE TITLE
Wrong date for latest version

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [hibbitts-design/grav-theme-quark-open-publishing#52]
Hi @paulhibbitts.
You recently released a new version of the theme and I was wondering if the date is correct. The changelog shows 2022 as the year, shouldn't it be 2024?

**Comment by paulhibbitts** [comment]
Hi @pmoreno-rodriguez , thanks for catching that! I will update the ChangeLog on GitHub but will likely not make another official Grav release at this time, hope that sounds ok🙂

**Comment by paulhibbitts** [comment]
I've been able to update the ChangeLog within the Release and the getgrav.org site picked up the change, so things are all fixed now without needing to do a another full release - thanks again @pmoreno-rodriguez

**Comment by pmoreno-rodriguez** [comment]
> I've been able to update the ChangeLog within the Release and the getgrav.org site picked up the change, so things are all fixed now without needing to do a another full release - thanks again @pmoreno-rodriguez

I have wanted to do this in one of my themes before, but I couldn't. Can you tell me how you did it? Thank you very much.

**Comment by paulhibbitts** [comment]
Sure thing @pmoreno-rodriguez , to update the current release files (but NOT update existing installs as this would require a new version release) I do the following:

1) Update files in theme (in this case this was just the ChangeLog)
2) Delete latest release on GitHub
3) Delete the tag for this same release
4) Make a new GitHub release with the SAME release tag

Hope that helps!

**Comment by pmoreno-rodriguez** [comment]
Thanks so much.
