### ISSUE TITLE
CSS seems to not being loaded correctly

### ISSUE THREAD

**Issue by Midas-sudo** [hibbitts-design/grav-theme-quark-open-publishing#53]
Just installed the theme on a brand new instalation of grav but he css doesn't seem to be loading correctly.

![image](https://github.com/user-attachments/assets/7d792deb-400c-47fc-a063-33c952c947a1)

The chrome dev tools don't appear to have any error. Am I missing any step? I ran bin/gpm install quark-open-publishing to install the theme.

Thank you  in advance

**Comment by Midas-sudo** [comment]
Nvm didnt understand I had to configure it in the themes. 

Now on anothe note. I tried replacing the default logo at the top with my own svg but the text doesnt change color when scrolling like the default. I notice the default is placed in the html as an svg but mine is as an image tag with the url set to my svg file 

![image](https://github.com/user-attachments/assets/15895bd8-752c-4e21-9e85-8d8f79880fa5)

**Comment by paulhibbitts** [comment]
Thanks for the issue. As a first step I would suggest trying the same customization with the parent Quark theme to see it's behaviour. If that is successful then try the same thing with the Open Publishing Skeleton, available on the getgrav.org downloads section.

Let me know how it goes, thanks!
